import type { Metadata } from "next";
// import localFont from "next/font";
import "./globals.css";

// const geistSans = localFont({
//   src: "",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Danphe International Consultancy Pvt. Ltd.",
  description: "Generated by Santosh Ghimire.",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body
          // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          className={`antialiased`}
        >
          {children}
        </body>
      </html>
    </>
  );
}
