import "./globals.css";

export const metadata = {
  title: "Danphe International Consultancy Pvt. Ltd.",
  description: "Generated by Santosh Ghimire.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
